owner: folkhart
repo: folkhart-status

sites:
  - name: Folkhart Game (Frontend)
    url: https://folkhart.netlify.app
    
  - name: Folkhart API
    url: https://backend-glre.onrender.com/api/health
    expectedStatusCodes:
      - 200
    
  - name: WebSocket Server
    url: https://backend-glre.onrender.com
    
assignees:
  - folkhart

status-website:
  cname: status.folkhart.com  # Optional: Your custom domain
  name: Folkhart Status
  introTitle: "⚔️ **Folkhart** Status"
  introMessage: Real-time status of Folkhart game services
  navbar:
    - title: Game
      href: https://folkhart.netlify.app
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Monitoring intervals
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"  # Check every 5 minutes
